arch: amd64

dist: bionic

language: go

go:
  - 1.15.x

before_install:
  - go get -t -v ./...

stages:
  - testing
  - coverage

jobs:
  include:
    - stage: testing
      script:
        - go test -v ./...
    - stage: coverage
      script:
        - go test -race -coverprofile=coverage.txt -covermode=atomic ./...

after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  email:
    recipients:
      - "saurab.mish@gmail.com"
    on_success: never
    on_failure: always
