version: 2

jobs:

  test:
    docker:
      - image: circleci/golang:1.15
    steps:
      - checkout
      - run: go test -v ./...

  cover:
    docker:
      - image: circleci/golang:1.15
    steps:
      - checkout
      - run:
          name: report coverage
          command: |
            go test -race -coverprofile=coverage.txt -covermode=atomic ./...
            bash <(curl -s https://codecov.io/bash)

workflows:
  version: 2
  build:
    jobs:
      - test
      - cover
